import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mockingbird</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
      <style jsx>{`
      .myImg{
        border-radius: 10px;

      }
      h2{
        font-size: 38px;

      }
      `}</style>

      <main className={styles.main}>
        <h1 className={styles.title}>Mockingbird</h1>

        <p className={styles.description}>
          A blog Mockingbird is for the coders to improve skills , bug fixes and
          more in easiest way.
        </p>
        {/* <img src="/coder.jpg" alt="img" width={250} height={160} className='myImg'/> */}
        <div className="blogs">

          <h2>Latest Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
        </div>
      </main>

      
    </div>
  );
}
