import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mockingbird</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={styles.mocknav}>
        
        <ul>
          <Link href="/">
            <a >
            <li>Home</li>


              </a>
          </Link>
          <Link href="/about">
            <a >
            <li>About</li></a>
          </Link>
          <Link href="/blog">
            <a ><li>Blog</li></a>
          </Link>
          <Link href="/contact">
      
            <a ><li>Contact</li></a>
          </Link>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>Mockingbird</h1>

        <p className={styles.description}>
          A blog Mockingbird is for the coders to improve skills , bug fixes and
          more in easiest way.
        </p>

        <div className="blogs">
          <h2>Popular Blogs</h2>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
          <div className="blogItem">
            <h3>How to learn JavaScript in 2k22</h3>
            <p>
              JavaScript is a programming language that allows you to write code
              that can be run on a web browser.
            </p>
          </div>
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
